apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - name: ui-app
        image: tbalaji/dockerimages:13
        ports:
        - containerPort: 8080
---



 apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: ui-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080       
